In [1]:
import numpy as np

In [8]:
arr_3d = np.array([[[1,2],[3,4],[5,6]],
                   [[7,8],[9,10],[11,12]]])

print(arr_3d.shape)

#indexing
print(arr_3d[0,1,1])

#Slicing 
print(arr_3d[:,:,1])


(2, 3, 2)
4
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#vectorization and broadcasting

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b)  # dont need loop


# broadcasting

a = np.array([1,2,3,4,5])
b = np.array([5])

print(a + b) # intellegently match the array b = 5,5,5,5,5

[11 22 33]
[ 6  7  8  9 10]


In [12]:
#Vector Normalization
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalize_arr = (arr-mean)/std_dev
print(normalize_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [ ]:
#Math important fux
#aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))

In [ ]:
#Power
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

In [ ]:
#Log and Exponential
arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))


In [ ]:
#Rounding
arr = np.array([1,2,3,4,5])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))